package com.sentinelflow.evidence;

public enum EvidenceRelationshipType {
    PERFORMED_BY, USED_DEVICE, OCCURRED_AT, GENERATED_FEATURE,
    USED_BY_MODEL, PRODUCED, CONTRIBUTES_TO, GOVERNED_BY,
    ASSOCIATED_WITH, SUPPORTS, CONTRADICTS, REFERENCES
}