package com.sentinelflow.evidence;

public enum EvidenceSourceType {
    TRANSACTION_RECORD, USER_ACTIVITY, DEVICE_HISTORY, LOCATION_HISTORY,
    MODEL_OUTPUT, RULE_ENGINE, POLICY_ENGINE, EXTERNAL_PROVIDER, INVESTIGATOR
}